global_exclude_dirs:
  - vendor
  - features
  - Tests
  - DataFixtures

rules:
  symfony.configuration.error_pages_should_be_customised: # we use FOSRest, so a custom "error" template is not necessary
    enabled: true
