preset: recommended

finder:
  exclude:
    - "app"
    - "web"
    - "var"

disabled:
  - unalign_equals

enabled:
  - align_equals
  - php_unit_construct
  - strict_param
  - strict
  - random_api_migration
