imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: locales.yml }

parameters:
    locale: en

# Framework Configuration
framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        name:        "SENSESSID"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        types:
            date_time_array: "AppBundle\\Service\\Doctrine\\Type\\DateTimeArrayType"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    User:
                        type:      annotation
                        is_bundle: false
                        dir:       "%kernel.root_dir%/../src/AppBundle/Model/User"
                        alias:     Account
                        prefix:    AppBundle\Model\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool:     { type: memory }

# Ma27ApiKeyAuthentication Configuration
ma27_api_key_authentication:
    user:
        object_manager: doctrine.orm.default_entity_manager
        model_name:     "AppBundle\\Model\\User\\User"
        password:
            strategy: php55
    api_key_purge:
        enabled: false

# FOSRest Configuration
fos_rest:
    body_listener:          true
    format_listener:        true
    param_fetcher_listener: true
    view:
        view_response_listener: force
        failed_validation:      HTTP_BAD_REQUEST
        default_engine:         twig
        formats:
            json:  true
            jsonp: true
            xml:   true
    format_listener:
        rules:
            - { path: ^/api, priorities: [html, json], fallback_format: ~, prefer_extension: false }
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true

# NelmioApiDoc Configuration
nelmio_api_doc:
    name:        "Sententiaregum REST API Docs"
    sandbox:
        enabled: true

# SncRedis Configuration
snc_redis:
    clients:
        doctrine_cache:
            type: predis
            alias: doctrine_cache
            dsn: "redis://localhost:%doctrine_redis_port%"
        online_users:
            type: predis
            alias: online_users
            dsn: "redis://localhost:%online_users_port%"
        blocked_users:
            type: predis
            alias: blocked_users
            dsn: "redis://localhost:%blocked_users_port%"

# Guzzle Configuration
guzzle:
    clients:
        freegeoip:
            base_url: "http://freegeoip.net"
            headers:
                Accept: "application/json"

# DoctrineMigrations Configuration
doctrine_migrations:
    dir_name:   "%kernel.root_dir%/migrations"
    namespace:  "Sententiaregum\\Migrations"
    table_name: "sententiaregum_migrations"
    name:       "Sententiaregum Migrations"

# DoctrineOrmBridge Configuration (SimpleBus)
doctrine_orm_bridge:
    entity_manager: default
    connection: default
