app:
    resource: "@AppBundle/Controller/"
    type:     annotation

initial:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: index.html.twig

ma27_api_key_authentication:
    resource: "@Ma27ApiKeyAuthenticationBundle/Resources/config/routing/routing.yml"
    prefix:   /api
