services:
  app.command.purge_ancient_auth_attempt:
    class: AppBundle\Command\PurgeAncientAuthAttemptDataCommand
    arguments:
      - "@app.repository.user"
    tags:
      - { name: console.command }
  app.command.purge_pending_activations:
    class: AppBundle\Command\PurgeOutdatedPendingActivationsCommand
    arguments:
      - "@app.repository.user"
    tags:
      - { name: console.command }
  app.command.load_custom_fixtures:
    class: AppBundle\Command\LoadCustomFixturesCommand
    tags:
      - { name: console.command }
    calls:
      - [setContainer, ['@service_container']]
