services:
  app.repository.user:
    class: AppBundle\Model\User\UserRepository
    public: false
    lazy: true
    factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
    arguments:
      - "Account:User"
  app.repository.role:
    class: Doctrine\ORM\EntityRepository
    public: false
    lazy: true
    factory: ["@doctrine.orm.default_entity_manager", 'getRepository']
    arguments:
      - "Account:Role"
