services:
  app.validator.locale:
    class: AppBundle\Validator\Constraints\LocaleValidator
    arguments:
      - "%app.locale_keys%"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.locale" }
  app.validator.unique_property:
    class: AppBundle\Validator\Constraints\UniquePropertyValidator
    arguments:
      - "@doctrine"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.unique_property" }
  app.validator.unique_dto_params:
    class: AppBundle\Validator\Constraints\UniqueDTOParamsValidator
    arguments:
      - "@property_accessor"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.unique_dto_params" }
